name: Build uf2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
       image: ghcr.io/pavelaron/uf2-build:1.20.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile Micropython
        run: ./build_rpi_pico_w.sh ${{ env.MICROPYTHON_VERSION }} ${{ env.NETWORK_HOSTNAME }}
      - name: Upload uf2 atrifact
        uses: actions/upload-artifact@v4
        with:
          name: "micropython-${{ env.NETWORK_HOSTNAME }}"
          path: ${{ github.workspace }}/micropython/ports/rp2/build-RPI_PICO_W/**/*
      - name: PNPM install
        run: pnpm install --no-frozen-lockfile
      - name: Minify
        run: pnpm start
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sesame
          path: ${{ github.workspace }}/dist/**/*
